---
micronaut:
  application:
    name: github-scraper
  http:
    services:
      github:
        urls:
          - https://api.github.com
  caches:
    most-starred-projects:
      maximumSize: 1
      expireAfterWrite: 30s

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
